server:
  port: 8050
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: auth-server
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-ms: 120000 # 2분 = 120,000ms
  refresh-token:
    expiration-ms: 86400000 # 24시간 = 86,400,000ms